name: terraform

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: "Plan"
        if: github.ref != 'refs/heads/master'
        run: terraform plan -input=false
        env:
          GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY }}
          GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET }}

      - name: "Apply"
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -input=false
        env:
          GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY }}
          GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET }}